global:
  scrape_interval: 5s # 5초마다 데이터 수집

scrape_configs:
  - job_name: 'digitaltok-server'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8080', 'localhost:8080'] # Spring 서버 주소 (network host 모드 기준)