name: CI/CD Pipeline

on:
  push:
    branches: [ develop ]  # develop 브랜치에 push가 일어날 때 실행

# Build 로직
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3  # 저장소 코드 체크아웃

      - name: Set up JDK 17  # Java 개발 킷 설정
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Make application.yml  # application.yml 파일 생성
        run: |
          cd ./src/main/resources
          echo "${{ secrets.APPLICATION_YML }}" > ./application.yml
        shell: bash

      - name: Grant execute permission for gradlew  # gradlew 실행 권한 부여
        run: chmod +x gradlew

      - name: Build with Gradle  # Gradle을 사용하여 프로젝트 빌드
        uses: gradle/gradle-build-action@v2
        env:
          # S3, RDS 연동
          DB_URL: ${{ secrets.DB_URL }}
          DB_USERNAME: ${{ secrets.DB_USERNAME }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
          AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_KEY }}
        with:
          arguments: build -x test

      - name: Upload build artifact  # 빌드된 아티팩트 업로드
        uses: actions/upload-artifact@v4
        with:
          name: digitalTok
          path: build/libs/*.jar

# 배포 로직
  deploy:
    needs: build  # build 작업이 성공적으로 완료된 후 실행
    runs-on: ubuntu-latest

    steps:
      - name: Download build artifact  # 이전 단계에서 업로드한 아티팩트 다운로드
        uses: actions/download-artifact@v4
        with:
          name: digitalTok
          path: build/libs/

      - name: Deploy to EC2  # EC2에 배포
        env:
          EC2_SSH_KEY: ${{ secrets.EC2_SSH_KEY }}
          EC2_USERNAME: ${{ secrets.EC2_USERNAME }}
          EC2_HOST: ${{ secrets.EC2_HOST }}

          # S3, RDS 연동
          DB_URL: ${{ secrets.DB_URL }}
          DB_USERNAME: ${{ secrets.DB_USERNAME }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
          AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_KEY }}
        run: |
          echo "$EC2_SSH_KEY" > private_key.pem
          chmod 600 private_key.pem
          jar_file=$(find build/libs -name '*.jar' ! -name '*plain.jar' | head -n 1)
          scp -i private_key.pem -o StrictHostKeyChecking=no "$jar_file" $EC2_USERNAME@$EC2_HOST:/home/$EC2_USERNAME/digitalTok.jar
          
          # 실행 스크립트(run.sh)를 로컬에서 생성.
          echo "pgrep java | xargs -r kill -15" > run.sh
          echo "sleep 5" >> run.sh
          
          # nohup 명령어 작성 (변수 값이 파일 안에 박제됩니다)
          echo "nohup java -Duser.timezone=Asia/Seoul \\" >> run.sh
          echo "  -Dspring.cloud.aws.region.static=ap-northeast-2 \\" >> run.sh
          echo "  -DDB_URL=\"${{ secrets.DB_URL }}\" \\" >> run.sh
          echo "  -DDB_USERNAME=\"${{ secrets.DB_USERNAME }}\" \\" >> run.sh
          echo "  -DDB_PASSWORD=\"${{ secrets.DB_PASSWORD }}\" \\" >> run.sh
          echo "  -DAWS_ACCESS_KEY=\"${{ secrets.AWS_ACCESS_KEY }}\" \\" >> run.sh
          echo "  -DAWS_SECRET_KEY=\"${{ secrets.AWS_SECRET_KEY }}\" \\" >> run.sh
          echo "  -jar /home/$EC2_USERNAME/digitalTok.jar > app.log 2>&1 &" >> run.sh
          
          # 만들어진 스크립트를 서버로 전송
          scp -i private_key.pem -o StrictHostKeyChecking=no run.sh $EC2_USERNAME@$EC2_HOST:/home/$EC2_USERNAME/run.sh
          
          # 서버에서 스크립트 실행
          ssh -i private_key.pem -o StrictHostKeyChecking=no $EC2_USERNAME@$EC2_HOST "sh /home/$EC2_USERNAME/run.sh"
          
          rm -f private_key.pem  # 민감한 정보 삭제